name: CI

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - master

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

defaults:
  run:
    shell: bash

env:
  CARGO_PROFILE_DEV_DEBUG: 0
  RUSTFLAGS: --deny warnings

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: Swatinem/rust-cache@v2

    - name: Clippy
      run: cargo clippy --all --all-targets

    - name: Format
      run: cargo fmt --all -- --check

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ripgrep shellcheck

    - name: Check for Forbidden Words
      run: ./bin/forbid

    - name: Check Install Script
      run: shellcheck www/install.sh

  msrv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.89.0

    - uses: Swatinem/rust-cache@v2

    - name: Check
      run: cargo check

  pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: Swatinem/rust-cache@v2

    - name: Install `mdbook`
      run: |
        curl --fail --silent --show-error --location \
          https://github.com/rust-lang/mdBook/releases/download/v0.4.52/mdbook-v0.4.52-x86_64-unknown-linux-gnu.tar.gz \
          | tar --extract --gzip --directory /usr/local/bin

    - name: Install `mdbook-linkcheck`
      run: |
        curl --fail --silent --show-error --location --remote-name \
          https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.7/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip
        unzip mdbook-linkcheck.x86_64-unknown-linux-gnu.zip mdbook-linkcheck -d /usr/local/bin
        chmod +x /usr/local/bin/mdbook-linkcheck

    - name: Build book
      run: |
        cargo run --package generate-book
        mdbook build book/en
        mdbook build book/zh

  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v6

    - uses: Swatinem/rust-cache@v2

    - name: Test
      shell: bash
      run: cargo test --all

    - name: Test install.sh
      shell: bash
      run: |
        bash www/install.sh --to /tmp --tag 1.25.0
        /tmp/just --version
